name: animated_layout
description: A widget that allows you to make layouts that can animate between sizing
version: 0.0.2
repository: https://github.com/ThinkDigitalSoftware/animated_layout

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: