name: animated_layout
description: A widget that allows you to make layouts that can animate between sizing
version: 0.1.0
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: